### ISSUE TITLE
quality_1vs1 not working correctly

### ISSUE THREAD

**Issue by tadhgfitzgerald** [sublee/glicko2#4]
quality_1vs1 doesn't seem to be computing the quality correctly.  Here's a snippet which demonstrates the problem. Two players play each other 5 times with one player always winning yet the quality score never changes.

```
   glicko_env = Glicko2()

    good_player = glicko_env.create_rating()
    bad_player = glicko_env.create_rating()

    for i in range(5):
        print(glicko_env.quality_1vs1(good_player, bad_player))
        good_player, bad_player = glicko_env.rate_1vs1(good_player, bad_player)
        print('Match {}: GP: {} - BP: {}'.format(i+1, good_player, bad_player))
```

**Comment by sublee** [comment]
I think the implementation of `quality_1vs1()` is totally wrong.  But I'm not currently maintaining this project.  Sorry about that.

I recommend you try http://trueskill.org/ instead.  It's also my project for another rating system.  It's much stable and I'm still maintaining it.  But if you need exact Glicko2, not any rating system, please find another implementation rather than this.
